# server
server:
  port: 80

# mybatis
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.best.entity
  mapper-locations: classpath:mapper/mysql/*.xml

# spring
spring:
  mvc:
    date-format: yyyy-MM-hh
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/java_learning_community?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: java_learning_community

# swagger
springfox:
  documentation:
    enabled: true
    auto-startup: true

# logging
logging:
  level:
    com:
      best:
        mapper: debug

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0

# chatgpt 代理端口
chatgpt:
  token: 1234
  proxy-host: 127.0.0.1
  proxy-port: 123456
  session-expiration-time: 300

