# server
server:
  port: 80

# mybatis
mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.best.entity
  mapper-locations: classpath:mapper/mysql/*.xml

# spring
spring:
  mvc:
    format:
      date: yyyy-MM-hh
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/java_learning_community?serverTimezone-UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: java_learning_community

# swagger
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: java_learning_community_swagger3.0
  try-host: http://localhost:${server.port}

# logging
logging:
  level:
    com:
      mao:
        mapper: debug

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0

# chatgpt 代理端口clash
chatgpt:
  token: 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
  proxy-host: 127.0.0.1
  proxy-port: 7890
  session-expiration-time: 300

